config/routes.rb
Rails.application.routes.draw do
  resources :user_allergens
  resources :ingredient_allergens
  resources :allergens
  resources :recipe_ingredients
  resources :ingredients
  resources :recipes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allergen.rb
class Allergen < ApplicationRecord
  has_many :ingredient_allergens
  has_many :ingredients, through: :ingredient_allergens

  has_many :user_allergens
  has_many :users, through: :user_allergens

  #returns number of users who are alergic to me
  def num_users_allergic
    self.users.count
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingredient_allergens
  has_many :allergens, through: :ingredient_allergens

  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  def allergic_to_me
    User.all.select do |user|
      user.allergens.any? {|allergen| self.allergens.include?(allergen) }
    end
  end

end

app/models/ingredient_allergen.rb
class IngredientAllergen < ApplicationRecord
  belongs_to :allergen
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  belongs_to :user

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_allergens
  has_many :allergens, through: :user_allergens

  has_many :recipes
end

app/models/user_allergen.rb
class UserAllergen < ApplicationRecord
  belongs_to :allergen
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to user_path(@recipe.user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/index.html.erb
<h1> 🍎 Ingredients 🍎 </h1>

<% if params[:sort] == "desc" %>
  <button>
    <%= link_to "Sort by Allergen # ⬆️", "#{ingredients_path}?sort=asc" %>
    <% @ingredients = @ingredients.sort { |ing|  ing.allergic_to_me.count }.reverse %>
  </button>
<% else %>
  <button>
    <%= link_to "Sort by Allergen # ⬇️", "#{ingredients_path}?sort=desc" %>
    <% @ingredients = @ingredients.sort { |ing|  ing.allergic_to_me.count } %>
  </button>
<% end %>

<ul>
  <% @ingredients.each do |ing| %>
  <li>
    <%= link_to "#{ing.name} - (#{ing.allergic_to_me.count})", ingredient_path(ing) %>
  </li>
  <% end %>
</ul>

app/views/ingredients/show.html.erb
<h1> <%= @ingredient.name %> </h1>

<h2>I am in these recipes:</h2>

<ul>
  <% @ingredient.recipes.each do |recipe| %>
  <li>
    <%= link_to recipe.title, recipe_path(recipe) %>
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergenApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1> 🍴 Recipes 🍴 </h1>

<% if params[:sort] == "desc" %>
  <button>
    <%= link_to "Sort by Ingredient # ⬆️", "#{recipes_path}?sort=asc" %>
    <% @recipes = @recipes.sort { |recipe|  recipe.ingredients.count }.reverse %>
  </button>
<% else %>
  <button>
    <%= link_to "Sort by Ingredient # ⬇️", "#{recipes_path}?sort=desc" %>
    <% @recipes = @recipes.sort { |recipe|  recipe.ingredients.count } %>
  </button>
<% end %>


<ul>
  <% @recipes.each do |recipe| %>
  <li>
    <%= link_to "#{recipe.title} - (#{recipe.ingredients.count})", recipe_path(recipe) %>
  </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>

<h2>I have authored these recipes:</h2>

<ul>
  <% @user.recipes.each do |recipe| %>
  <li>
    <%= link_to recipe.title, recipe_path(recipe) %>
    <button>
      <%= link_to "delete", recipe_path(recipe), method: :delete %>
    </button>
  </li>
  <% end %>
</ul>